// Copyright 2018-2021 System76 <info@system76.com>
//
// SPDX-License-Identifier: GPL-3.0-only

use std::{
    fs,
    io::{self, Write},
    path, process,
};

use super::error::GraphicsDeviceError;
use super::mode::GraphicsMode;
use super::systemd;

// ── File paths ───────────────────────────────────────────────────────────────

pub(crate) const MODPROBE_PATH: &str = "/etc/modprobe.d/system76-power.conf";
pub(crate) const PRIME_DISCRETE_PATH: &str = "/etc/prime-discrete";

/// Models whose every external display output routes through the dGPU.
/// Runtime switching is unsafe on these because removing the dGPU while an
/// external display is connected would kill that output entirely.
pub(crate) const EXTERNAL_DISPLAY_REQUIRES_NVIDIA: &[&str] = &[
    "addw1",
    "addw2",
    "addw3",
    "addw4",
    "addw5",
    "bonw15",
    "bonw15-b",
    "bonw16",
    "gaze14",
    "gaze15",
    "gaze16-3050",
    "gaze16-3060",
    "gaze16-3060-b",
    "gaze17-3050",
    "gaze17-3060-b",
    "gaze20",
    "kudu6",
    "oryp4",
    "oryp4-b",
    "oryp5",
    "oryp6",
    "oryp7",
    "oryp8",
    "oryp9",
    "oryp10",
    "oryp11",
    "oryp12",
    "oryp13",
    "serw13",
    "serw14",
];

// ── Modprobe templates ───────────────────────────────────────────────────────

// Write an empty file to ensure old values are removed.
static MODPROBE_EMPTY: &[u8] = br"# Automatically generated by system76-power
";

static MODPROBE_COMPUTE: &[u8] = br"# Automatically generated by system76-power
blacklist nvidia-drm
blacklist nvidia-modeset
alias nvidia-drm off
alias nvidia-modeset off
";

static MODPROBE_INTEGRATED: &[u8] = br"# Automatically generated by system76-power
blacklist nouveau
blacklist nvidia
blacklist nvidia-drm
blacklist nvidia_uvm
blacklist nvidia-modeset
alias nouveau off
alias nvidia off
alias nvidia-drm off
alias nvidia-uvm off
alias nvidia-modeset off
";

// ── Suspend/sleep option templates ───────────────────────────────────────────

// Systems that cannot use other sleep options.
static SYSTEM_SLEEP_EMPTY: &[u8] = b"";

// Systems using S0ix must enable S0ix-based power management.
static SYSTEM_SLEEP_S0IX: &[u8] = br"# Preserve video memory through suspend
options nvidia NVreg_EnableS0ixPowerManagement=1
";

// Systems using S3 had suspend issues with WebRender.
static SYSTEM_SLEEP_S3: &[u8] = br"# Preserve video memory through suspend
options nvidia NVreg_PreserveVideoMemoryAllocations=1
";

// ── Xorg config template ─────────────────────────────────────────────────────

// The use of hybrid or discrete is determined by the "PrimaryGPU" option.
static XORG_CONF_DISCRETE: &[u8] = br#"# Automatically generated by system76-power
Section "OutputClass"
    Identifier "NVIDIA"
    MatchDriver "nvidia-drm"
    Driver "nvidia"
    Option "PrimaryGPU" "Yes"
    ModulePath "/lib/x86_64-linux-gnu/nvidia/xorg"
EndSection
"#;

// ── Path helpers ─────────────────────────────────────────────────────────────

pub(crate) fn get_xorg_conf_path() -> &'static str {
    if path::Path::new("/etc/X11/xorg.conf.d").exists() {
        "/etc/X11/xorg.conf.d/11-nvidia-discrete.conf"
    } else {
        "/usr/share/X11/xorg.conf.d/11-nvidia-discrete.conf"
    }
}

/// Returns the initramfs rebuild command and its single argument.
///
/// Exposed as `pub(crate)` so the daemon can invoke it from a background task
/// after a runtime switch, without blocking the D-Bus call.
pub(crate) fn update_initramfs_cmd() -> (&'static str, &'static str) {
    if path::Path::new("/usr/bin/dracut").exists() {
        ("reinstall-kernels", "")
    } else {
        ("update-initramfs", "-u")
    }
}

// ── PRIME helper ─────────────────────────────────────────────────────────────

pub(crate) fn get_prime_discrete() -> Result<String, GraphicsDeviceError> {
    fs::read_to_string(PRIME_DISCRETE_PATH)
        .map_err(GraphicsDeviceError::PrimeModeRead)
        .map(|mode| mode.trim().to_owned())
}

pub(crate) fn set_prime_discrete(mode: &str) -> Result<(), GraphicsDeviceError> {
    fs::write(PRIME_DISCRETE_PATH, mode).map_err(GraphicsDeviceError::PrimeModeWrite)
}

// ── Config writer ─────────────────────────────────────────────────────────────

/// Write all configuration files for the given graphics mode.
///
/// This is the shared core used by both `set_vendor` (boot-time path) and
/// `switch_runtime` (no-reboot path). It does NOT rebuild the initramfs —
/// callers are responsible for that step.
pub(crate) fn write_vendor_config(vendor: GraphicsMode) -> Result<(), GraphicsDeviceError> {
    let mode = match vendor {
        GraphicsMode::Hybrid => "on-demand\n",
        GraphicsMode::Discrete => "on\n",
        _ => "off\n",
    };

    let bonw15_hack = {
        let dmi_vendor = fs::read_to_string("/sys/class/dmi/id/sys_vendor").unwrap_or_default();
        let dmi_model = fs::read_to_string("/sys/class/dmi/id/product_version").unwrap_or_default();
        matches!(
            (dmi_vendor.trim(), dmi_model.trim()),
            ("System76", "bonw15") | ("System76", "bonw15-b")
        )
    };

    // Configure X server
    if vendor == GraphicsMode::Discrete {
        let mut file = fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(get_xorg_conf_path())
            .map_err(GraphicsDeviceError::XserverConf)?;
        file.write_all(XORG_CONF_DISCRETE)
            .and_then(|()| file.sync_all())
            .map_err(GraphicsDeviceError::XserverConf)?;
    } else if path::Path::new(get_xorg_conf_path()).exists() {
        fs::remove_file(get_xorg_conf_path()).map_err(GraphicsDeviceError::XserverConf)?;
    }

    // Write modprobe config
    {
        log::info!("Creating {}", MODPROBE_PATH);

        let mut file = fs::OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(MODPROBE_PATH)
            .map_err(GraphicsDeviceError::ModprobeFileOpen)?;

        let text = match vendor {
            GraphicsMode::Integrated => MODPROBE_INTEGRATED,
            GraphicsMode::Compute => MODPROBE_COMPUTE,
            _ => MODPROBE_EMPTY,
        };

        file.write_all(text)
            .and_then(|()| file.sync_all())
            .map_err(GraphicsDeviceError::ModprobeFileWrite)?;

        // Power management must be configured depending on whether the system
        // uses S0ix or S3 for suspend.
        if vendor != GraphicsMode::Integrated {
            // XXX: Better way to check?
            let s0ix =
                fs::read_to_string("/sys/power/mem_sleep").unwrap_or_default().contains("[s2idle]");

            let (sleep, action) = if bonw15_hack {
                (SYSTEM_SLEEP_EMPTY, "disable")
            } else if s0ix {
                (SYSTEM_SLEEP_S0IX, "enable")
            } else {
                (SYSTEM_SLEEP_S3, "enable")
            };

            // We should also check if the GPU supports Video Memory Self
            // Refresh, but that requires already being in hybrid or nvidia
            // graphics mode. In compute mode, it just reports '?'.

            file.write_all(sleep)
                .and_then(|()| file.sync_all())
                .map_err(GraphicsDeviceError::ModprobeFileWrite)?;

            for service in
                &["nvidia-hibernate.service", "nvidia-resume.service", "nvidia-suspend.service"]
            {
                let status = process::Command::new(systemd::SYSTEMCTL_CMD)
                    .arg(action)
                    .arg(service)
                    .status()
                    .map_err(|why| GraphicsDeviceError::Command {
                        cmd: systemd::SYSTEMCTL_CMD,
                        why,
                    })?;

                if !status.success() {
                    // Error is ignored in case this service is removed
                    log::warn!(
                        "systemctl {} {}: failed with {} (not an error if service does not \
                         exist!)",
                        action,
                        service,
                        status
                    );
                }
            }
        }
    }

    log::info!("Setting {} to {}", PRIME_DISCRETE_PATH, mode);
    set_prime_discrete(mode)?;

    // Enable or disable nvidia-powerd based on the graphics mode.
    let action = match vendor {
        GraphicsMode::Compute | GraphicsMode::Hybrid | GraphicsMode::Discrete => {
            log::info!("Enabling NVIDIA services");
            "enable"
        }
        GraphicsMode::Integrated => {
            log::info!("Disabling NVIDIA services");
            "disable"
        }
    };

    for service in &["nvidia-powerd.service"] {
        let status = systemd::systemctl(&[action, service])
            .map_err(|why| GraphicsDeviceError::Command { cmd: systemd::SYSTEMCTL_CMD, why })?;

        if status.success() {
            log::info!("{}d {}", action, service);
            continue;
        }
        // Error is ignored in case this service is removed
        log::warn!("systemctl: failed with {} (not an error if service does not exist!)", status);
    }

    Ok(())
}
