on:
  push:
    branches: [master]
  pull_request:

name: Continuous integration

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup toolchain install nightly --component rustfmt
      - name: fmt
        run: cargo +nightly fmt --all --check

  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - name: install system dependencies
        run: sudo apt-get update && sudo apt-get install libdbus-1-dev libusb-1.0-0-dev
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup show
      - name: clippy
        run: cargo clippy --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: install system dependencies
        run: sudo apt-get update && sudo apt-get install libdbus-1-dev libusb-1.0-0-dev
      - uses: actions/checkout@v3
      - name: install toolchain
        run: rustup show
      - name: test
        run: cargo test --all-features
